name: CI-Composite
on:
 workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Node build
          uses: selflearner2025/company-devops/actions/node-build@master
          with:
            node-version: "22"
