name: CI

on:
    #push:
    #pull_request:
    workflow_dispatch:
jobs:
  ci:
    uses: selflearner2025/company-devops/.github/workflows/reusable-ci.yml@master
    with:
        node_version: "22"
        run_tests: false



